### ISSUE TITLE
Props should always available when component init.

### ISSUE THREAD

**Issue by iineva** [jaredpalmer/after.js#105]
This code works well on SSR. But don't works on client side when route change to this component.

```jsx
export default class TestComponent extends Component {
  state = {
    messages: this.props.messages || [],
  }

  static getInitialProps = async () => ({
    messages: await loadMessage(),
  })

  render() {
    return this.state.messages.map(row =>
      <h1>{row.title}</h1>
    )
  }
}
```

**Comment by jaredpalmer** [comment]
This is a design decision. It allows for Instagram-like loading behavior:

- race a timeout for 500ms against the presence of props. Render null in the meantime. If props finish first, render them. 
- After 500ms, if still no props, render loading indicator for 1s. Once elapsed, check again if props exist. If they do, render them, otherwise render loading indicator until they do.
