### ISSUE TITLE
Redirecting from getInitialProps with res.redirect() causes error

### ISSUE THREAD

**Issue by fi5u** [jaredpalmer/after.js#109]
When using `res.redirect()` in `getInitialProps()`, I get the following error:

```
(node:73586) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Can't set headers after they are sent.
```

The code is simply:

```
static async getInitialProps({ req, res, match, history, location, ...ctx }) {
    res.redirect('/');
}
```

The redirect **does** occur, but am I missing something due to the error?

**Comment by felipeleusin** [comment]
I think it's best to leave the redirect to using <Redirect > on the render method of the component since it will work on both the client and the server OR in server.js (you can use a middleware) if you just want to leave it on the server

**Comment by fi5u** [comment]
Ok, thanks for the info.

**Comment by fi5u** [comment]
@pcraig3 Sorry, no. The project was abandoned shortly after.

**Comment by jaredpalmer** [comment]
getInitialProps must be able to run on both client and server. You could check for res and all res.redirect but if it’s undefined call window.location.replace

**Comment by alidcastano** [comment]
This still causes the same error: 

```

    if (ctx.res && ctx.res.redirect) {
      ctx.res.redirect('/home')
    } else {
      window.location.replace('/home')
    }
```


```
(node:36120) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): Error: Can't set headers after they are sent
```

**Comment by alidcastano** [comment]
The problem is that even if you redirect, the responose is still being sent in server.js which leads to conflicting headers

So btw @pcraig3 the only way I've gotten this to work is by definiing the redirects inside sever.js and returning early

**Comment by pcraig3** [comment]
🎉 

Just got this to work without throwing an error.

## problem 😫

As you noted, @alidcastano, the default behaviour of the `.get` route is to [always return `res.send(html)`](https://github.com/jaredpalmer/after.js/blob/master/examples/basic/src/server.js#L11-L23). [As noted elsewhere](https://github.com/mozilla/nunjucks/issues/652#issuecomment-400371774), if you call `res.send` or `res.redirect` multiple times in a row, then express is unhappy. 

So, if we write 
```javascript
// server.js
 .get('/*', async (req, res) => {
    try {
      const html = await render({
        // ...
      });
     res.redirect('/');  // <-- it _will_ redirect but also throw an error
     res.send(html);
    } catch (error) {
      res.json(error);
    }

```
(ignoring that we have an infinite loop) then we get `Error: Can't set headers after they are sent.`

Instead, we have to explicitly return the response when we are done with it
```javascript
// server.js
 .get('/*', async (req, res) => {
    try {
      const html = await render({
        // ...
      });
     return res.redirect('/');  // <-- now it works
     res.send(html);  // <-- this code is unreachable
    } catch (error) {
      res.json(error);
```

So that's what we want.

When we're in the `getInitialProps` for a component, we aren't able to return the `res` to end the request. Writing `return res.redirect('/')` in `getInitialProps` will just take us to component's constructor earlier.
We're still queuing up a `res.redirect` followed by a `res.send` once we're back in the server. 
This is why we get the `Error`: we're doing the same thing as in scenario 1.

## solution 💡

We can do the redirect here if we figure out a way to pass a value back.

```javascript
// server.js
 .get('/*', async (req, res) => {
    try {
      const html = await render({
        // ...
      });

     if(ifRedirect === true) {
       return res.redirect('/');
     }
     res.send(html);
    } catch (error) {
      res.json(error);
    }
```

So I was clicking around the express docs when I found [`res.locals`](https://expressjs.com/en/api.html#res.locals). This is pretty much exactly what we want.

So now we can do an error-free server-side redirect:

```javascript
// Page.js
class Page extends Component {
  static async getInitialProps({ res, req, match }) {
    res.locals.redirect = '/about'
  })
  // ...
}

// server.js
 .get('/*', async (req, res) => {
    try {
      const html = await render({
        // ...
      });

    return res.locals.redirect ? 
      res.redirect(res.locals.redirect)
      res.send(html);
    } catch (error) {
      res.json(error);
    }
```

Hope that helps you out! 
(Might also be useful for your other issue, #146 as well)

**Comment by alidcastano** [comment]
You can also check if `res.finished` and if so return early. That's how I handled it. Sorry I didn't put code above maybe would have saved you some time
```
 .get('/*', async (req, res) => {
    try {
      const html = await render({
        // ...
      });

    return res.locals.redirect ? 
      if (res.finished) return // if redirect, it'll happen on it's own
      res.send(html);
    } catch (error) {
      res.json(error);
    }
```

But anyway I've moved on from Afterjs because of basic things like this and decided to make my own solution :) will be releasing soon

**Comment by pcraig3** [comment]
Yeah, that works as well. I couldn't find `.finished` in the express docs, but that seems like a pretty good solution as well.

**Comment by kasbah** [comment]
> Did you figure out a way to get it redirecting in the render method of the component?

The way to redirect  in render by the way is:

```js
import {Redirect} from 'react-router-dom'

class MyComponent extends React.Component {
  render() {
    return <Redirect to='/wherever' />
  }
}
```

Check the [react-router docs](https://reacttraining.com/react-router/web/api/Redirect) if you need to know more.

**Comment by miracle2k** [comment]
The `render()` function has multiple instances where it handles a redirect, and returns `undefined` in all cases except the last one (https://github.com/jaredpalmer/after.js/blob/666d1b4ecd74b4355d6a4d3f14443ebacb734094/packages/after.js/src/render.tsx#L121).

If render() simply returned `undefined` in that last case as well, or, returned that information in some other way, our code in `server.js` could deal with it accordingly. Of course, `res.finished` as suggested above seems like a good solution as well - maybe it should be included in the `server.js` samples.

**Comment by nimaa77** [comment]
umm

why you don't use the new Redirect feature, you just return an object like this and after.js will do the rest

```js
Page.getInitialProps = async ({ match }) => {
  // default status code is 302 (you can override it)
  return { redirectTo: '/foo' };
};
```

works both on the server and the client

**Comment by nimaa77** [comment]
also, using `<Redirect />` is expensive

because at first `after.js` should call the `getInitalProps` for the matched Page and then it will render the react tree (calling `ReactDOMServer.renderToString` method)

if you handle redirect in the getInitialProps you are not going to waste CPU cycles on `renderToString` ...

**Comment by Superoryco** [comment]
@pcraig3 `finished` is now changed to `writableEnded`.
I solve the problem as following:

```javascript
	try {
		const html = await render({
			req,
			res,
			routes,
			assets,
			// @ts-ignore
			document: Document,
			customRenderer,
			// @ts-ignore
			store,
		});
		if (!res.writableEnded) {
			res.send(html);
		}
	} catch (error) {
		console.error({ error });
		if (!res.writableEnded) {
			res.json(error);
		}
	}
```

@nimaa77 I know using  `<Redirect />` is much more expensive then dealing redirect in `getInitalProps `, however, in my case: I use one big component called 'MainPage', and handles all the initial data from server(eg. currentUser, could be null if Unauthenticated.), for some pages there is no extra specific data required in `getInitialProps`(compare to other pages), so I have to use `<Redirect />` in react render to tell the client side that authentication is required if currentUser is null. Do you have more elegant way to do this? May be we could update the server.js samples, OR, solve this in `function render<T>(options: AfterRenderOptions<T>)` method?

**Comment by Tooluloope** [comment]
Had this same error but noticed it goes when I restart my server but once I make changes to getInitialProps, I start seeing the server error
