### ISSUE TITLE
Not working with React Router v5

### ISSUE THREAD

**Issue by stepanh** [jaredpalmer/after.js#209]
## Bug
`react-router-dom@4.3.1` works fine.
`react-router-dom@5.0.0` causes this code in `client.(js|tsx)`
```
ensureReady(routes).then((data) =>
  hydrate(
```
to explode with `"You should not use <Route> outside a <Router>"`

- After.js Version: 1.3.1

_I can put together a sample repo, if needed (and maybe I'll try to look into it)._

**Comment by FreeLineTM** [comment]
Don't believe this should be closed until #215 is merged.

**Comment by sch** [comment]
> Closed due to inactivity. Holler if this is a mistake, and we'll re-open it.

It might be a mistake. Running into something similar, and I think it may be because of an incompatibility in `react-router` versions. My lockfile is resolving two separate versions, one using the informal `context` api, and one using the new `context` api. This causes an error to be thrown on the client that a component expecting a router's context is missing, event though it's being rendered as a child of `BrowserRouter`.
