### ISSUE TITLE
Should we be transpiling lib?

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/after.js#23]
Everything is copied into from lib to `./build/src` so it can theoretically be overridden in user land. However, I'm pretty sure that publishing any untranspiled code to npm is generally considered a bad idea. On the other hand, we can 100% guarantee that this is _going_ to be transpiled. So idk. Thoughts? 

cc @gaearon

**Comment by prichodko** [comment]
I believe Dan is @gaearon here on Github.

**Comment by jaredpalmer** [comment]
Heh i forgot

**Comment by gaearon** [comment]
My thoughts on this:

* You shouldn't attempt to compile any non-JS things like JSX/Flow/stage-X because this fragments the ecosystem and locks people into particular build tools. Imagine wanting to update to Babel 8 only to learn that some transitive runtime dependency happens to use a transform for a dropped proposal and that doesn't exist anymore.

* However it's also probably not feasible to *not* compile anything at all because Node moves faster than browsers, and in general it's unreasonable to expect package maintainers to care about compiling to ES5 (or any other baseline) anymore.

My conclusion from this was that we should:

* Compile app code with bells and whistles we consider reasonable.
* Compile `node_modules` strictly with `babel-preset-env`, explicitly making sure we *don’t* respect `.babelrc` in dependencies.

Note that even this is only safe (or at least not-definitely-broken) with Babel 7 because Babel 6 opts all files into strict mode whether they’re written as strict or not. So running Babel 6 over dependencies *does* break them but running Babel 7 over them *shouldn’t* (but could in theory—we need to verify this on larger dep trees).

Our implementation of the workflow I just described is here: https://github.com/facebookincubator/create-react-app/pull/3776. Hope you can find it helpful.

**Comment by jaredpalmer** [comment]
Thanks @gaearon. That's super helpful. I guess this comes down to whether people will end up trying to use stuff in the `lib` directory outside of After.js. My guess is no they will not at the moment. If we ever do move things like ensureReady and loadInitialProps elsewhere, we should def transpile first.
