### ISSUE TITLE
Compatible with loadable-components?

### ISSUE THREAD

**Issue by hornta** [jaredpalmer/after.js#386]
## ❓Question
Hello. I've just setup Razzle.js and it's working great and now I want to explore component based code splitting. I have used https://github.com/gregberge/loadable-components before and want to be able to use it here but I'm unsure if it's possible since After.js itself has the asyncComponent method?

**Comment by dodas** [comment]
Yes, it does work.
Check out the [with-loadable-components](https://github.com/dodas/razzle/tree/patch-1/examples/with-loadable-components) example.

In my fork, I just fixed few reference errors found in original `server.js`

**Comment by nimaa77** [comment]
hey, yes it's possible but there is a problem with `loadable-components`

we have `getInitialProps` as a static property of the `component`

when you lazy load your component with `loadable-components` after.js can't access the `getInitialProps` property because the object you pass to after.js is actually a `loadable-components` object and there is no `getInitialProps` on that object

that being said, you can use `loadable-components` for components that don't to have `getInitialProps`...

**Comment by dodas** [comment]
For route components (the only components that use getInitialProps?) you will use `asyncComponent` from after.js anyway, don't you?

**Comment by nimaa77** [comment]
yes exactly 

I think there is a hack around `loadable-components` which will help you to access the `getInitialProps`

**Comment by nimaa77** [comment]
check this out

https://stackoverflow.com/a/56610365/4828470
