### ISSUE TITLE
Managing secret code & logic

### ISSUE THREAD

**Issue by eran-pinhas** [jaredpalmer/after.js#400]
Hi there :)

Was wondering about a security "problem" (apostrophes as I'm not sure if I'm right about it)

I going to assume every server has some secret stuff that can be divided into 2 types - configurations (files, passwords...) and logic (algorithms, SQL queries, business logic...)

I do understand that secret **configuration** should be managed  through `.env` or other environment variable solution

But IMHO secret **logic** has a problem - it is being bundled into the the `.js` file that's being delivered into the client. Say, if I have a DAL function that's querying some SQL - the SQL itself and what I'm doing with the data afterwards is being imported to the component file that in turn being bundled (but of course not being called in the client) and this is quite problematic

Not sure if I'm missing something or it is indeed a problem, 

Appreciate it!
Eran

**Comment by nimaa77** [comment]
Hi, this problem is not related to after.js but I will answer it here

if you are using razzle for your webpack configuration razzle will build your app two times with two different entry points

index.js (server-side code that hosted on our servers)
client.js (client-side that browser will get and use to rehydrate our app)
and most of our app logic is shared between server and client (I mean React Components!) and there are some functions that we only want to use them on the server-side (it's not shared between server and client and we are going to use them in server-side)

let's assume you have a file called `connection.js` which handles a connection to a MongoDB instance 

```js
// ./src/db/connection.js
import { MongoClient } from "mongodb";

const uri = proccess.env.RAZZLE_MONGODB_CONNECTION_STRING;
const client = new MongoClient(uri);
```
and inside the `.env` file we have:

```env
RAZZLE_MONGODB_CONNECTION_STRING = "mongodb+srv://<username>:<password>@<your-cluster-url>/db";
```

if you import `connection.js` inside `index.js` or `server.js` or any files that only get handled on the server-side, logically there should not be any footprint of `connection.js` in the client bundle since we didn't use it on shared logic or client-side code.

**Comment by nimaa77** [comment]
also, webpack tree shaking and teaser plugin will do some cool things for us

when we run build command all `process.env` properties get replace by the actual values for example if we have `process.env.NODE_ENV` it's going to get replaced to "production"

this code block
```js
import { foo, bar } from "./utils"

if (process.env.NODE_ENV === "development") {
  foo()
} else {
  bar()
}
```
will change to

```js
import { foo, bar } from "./utils"

if ("production" === "development") {
  foo()
} else {
  bar()
}

```

and "production" === "development" is always false so the teaser plugin will understand this and removes the code block that has `foo()`

```
import { foo, bar } from "./utils"

{
  bar()
}

```

and since foo is not used and we are using es-modules import syntax if will get removed from the final bundle

there is an env variable for build target which will tell you what razzle is currently working on
```env
process.env.BUILD_TARGET: either 'client' or 'server'
```

you can use this to achieve the same thing 😉

**Comment by eran-pinhas** [comment]
Thank you very much @nimaa77 

This is more a discussion rather than a question I have, and would love to take part is solving what I believe is problematic

- I do think it's related to _after_ (or any other React SSR framework in that matter) - because there is a problem that should be addressed, either in the framework or the docs.
- Your first answer is relevant for code that's being imported from `server.js` or `index.js` but a lot of sensitive code will be imported to be called at `getInitialProps` which **is** being bundled
- The tree shaking solution seems legit but -
  1. I believe that as a SSR framework we should have a built-in solution the sensitive code bundling __**__
  2. If it's impossible (or we decide it's outside the framework scope) - I do think we should have a docs section that would make developers consider this issue

 __**__ Solutions I can think of:
- Somehow providing razzle file patterns that files shouldn't be included in the client bundle (using regex / folder names / file names). but I'm not sure how it would manage the vars/functions  that are being imported but are not available
- Purging the potential problematic functions (e.g `getInitialProps`) before starting the bundle - so hopefully the tree shaking will remove it... it is more elegant and automatic but in my opinion not explicit enough and is not foolproof
- Having the potential problematic functions (e.g `getInitialProps`) configured to the route & the component in a different file that is not being bundled

**Comment by nimaa77** [comment]
I got your point but handling SQL-queries in getInitalProps is totally wrong

getInitalProps get called on both client and server and I don't think it's generally a good idea to connect to a database from the client-side (why do we even need backends in that case :D)

and if we want to think about it from out of the box, you can't find any edge case for the secrets (if you don't go crazy with getInitalProps)

Just open a pull request and add anything that you think may be useful for other developer

**Comment by eran-pinhas** [comment]
Wait, why sould `getInitalProps ` be called on the client side? It doesn't make sense

I know it is being bundled (that what troubles me, because it bring the dependencies with it - e.g the DAL code) but it shouldn't be called in the client

**Comment by nimaa77** [comment]
when you navigate between pages on the client-side, `after.js` first calls getInitialProps to get data for the page, and then after the returned promise from getInitialProps gets resolved it shows the next page
