### ISSUE TITLE
Layout pages

### ISSUE THREAD

**Issue by Lucanis** [jaredpalmer/after.js#47]
Nice work, this looks really promising.

I have a small question, is there a way to define a layout, to reuse a component on each page (e.g., a navigation component) ?

**Comment by StevenLangbroek** [comment]
It's React, so you don't need anything specific from after.js..., i.e.:

layout.js:
```jsx
import React from 'react';
import Navigation from './Navigation';

export default function Layout(props) {
  return (
    <div>
      <Navigation />
      <div class="main">
        {props.children}
      </div>
    </div>
  );
}
```

then in your page just do:

```jsx
function MyPage(props) {
  return (
    <Layout>
      <h1>My page!</h1>
    </Layout>
  );
}
```

**Comment by jaredpalmer** [comment]
How would ppl feel about a top level Root component from which all routes inherit. Right now this is `_app.js` which is part of After. However, we could allow users to write their own.

**Comment by StevenLangbroek** [comment]
Could this also help with misc `<Provider>`s?

**Comment by jaredpalmer** [comment]
Yes. Unlike next.js, where you need to keep around a lot of HoC's to accomplish this (e.g. `withData()`), with this kind of setup you could wrap things on your own. 

### Route Config

```js
// ./src/_routes.js

// ...imports

export default [{
   path: '/',
   component: Root, // providers could go here
   routes: [
       {
         path: '/',
         component: Home,
         exact: true
       },
       {
         path: '/about',
         ...
       }
   ]
}]
```

However, this wouldn't be perfect. For example, if you need to create a different router than BrowserRouter or you want to wrap your entire client app (including the router) in a provider. For example, this solution won't work with react-router-redux. https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux

**Comment by jaredpalmer** [comment]
I wonder if it makes sense allow users to copy and paste `_client.js`. This was my initial idea. Seems much better than trying to find a "framework" solution.

**Comment by pronevich** [comment]
I think "layout" components are uncovered issue in ssr land and after.js has the chance to change this in the "right" way:


1. Don't put <SomeLayout /> component on each page. Layout defines route point not the page. Then pages go under layout.
```javascript
```
2.

**Comment by frol** [comment]
@jaredpalmer Should the demonstrated router config work? My small experiment ended up with only Root component, and anything that is in the nested `routes` just seems to be ignored.

**Comment by StevenLangbroek** [comment]
@frol did you remember to pass `props.children` through?

**Comment by frol** [comment]
Here is the `props` in the `Root` component:

![screenshot from 2018-01-18 15-34-13](https://user-images.githubusercontent.com/304265/35100611-183c36a2-fc65-11e7-86e9-ec97cc11f791.png)

(NOTE: no `children`)

```jsx
import React from 'react'

export default class extends React.PureComponent {
  render() {
    console.log(this.props)
    return (
        <div>
            <h1>Head</h1>
            {this.props.children}
            <h1>Tail</h1>
        </div>
    )
  }
}
```

**Comment by pronevich** [comment]
I think "layout" components are uncovered issue in ssr land and after.js has the chance to change this in the "right" way:

1. Don't import same layout component on each page. Sometimes layout, not the page, defines route point. Then pages go under the layout. Something that @jaredpalmer proposed:

```javascript
export default [{
   path: '/',
   component: Root, //  providers could go here and RootLayout if needed 
   routes: [
       {
         path: '/',
         component: Home, // will be under RootLayout
         exact: true
       },
       {
         path: '/user',
         component: UserLayout,
       },
       {
         path: '/user/login',
         component: LoginComponent // will be under UserLayout
       },
       ...
   ]
}]
```

2. Layout can be split point too. `import('UserLayot')`
3. On next route under the same layout, we loading only PageComponent, because of 1.

**Comment by felipeleusin** [comment]
Is there a reason for this issue been closed? Also got hit with this but couldn't find a fix in the source.  We were thinking about how to fix it and the one that makes most sense specially considering the motto of "what if next.js and react-router had a baby" was to be able to use nested routing like react-router-config. Are you open to a PR using it? 

Otherwise I can think of being able to send a Layout prop to render that gets injected into the After (afterparty) component and it defaults to Fragment. Then we can just include this component again in client.js

**Comment by alexparish** [comment]
@jaredpalmer What's the current advice on setting up a shared layout page?
